export const supportedLocales = [
  { code: "en", label: "English" },
  { code: "km", label: "ខ្មែរ" },
];

const localeKey = "emenu_locale";

const dictionary = {
  en: {
    addToCart: "Add to cart",
    addedToCart: "added",
    cart: "Cart",
    cartEmpty: "Cart is empty",
    backToMenu: "Back to menu",
    checkout: "Checkout",
    checkoutDescription: "Review your items, add customer details, and submit your order to the restaurant.",
    checkoutStepReview: "Review items",
    checkoutStepDetails: "Add details",
    checkoutStepSend: "Send order",
    chooseProduct: "Choose a product to start an order.",
    clearSearch: "Clear search",
    customerDetails: "Customer details",
    customerDetailsHelp: "These details help the restaurant confirm and prepare your order.",
    customerName: "Customer name",
    customerPhone: "Phone",
    dineIn: "Dine in",
    each: "each",
    emptyCartMessage: "Return to the menu and choose a product.",
    featured: "Featured",
    free: "Free",
    freshMenu: "Fresh menu, ready to order.",
    isRequired: "is required",
    itemTypes: "item types",
    loadingMenu: "Loading menu...",
    mainBranch: "Main branch",
    menu: "Menu",
    noDescription: "No description",
    noImage: "No image",
    noProductsFound: "No products found",
    optional: "Optional",
    optionRequiredHelp: "Required for this item",
    optionOptionalHelp: "Optional add-on",
    orderNote: "Order note",
    orderSubmitted: "Order submitted",
    orderReceivedDescription: "Your order was sent to the restaurant. The kitchen will prepare it next.",
    orderNextStep: "Keep this page open to follow order and payment updates.",
    orderStatusTimeline: "Order status timeline",
    reconnectOrderStatus: "Reconnect to refresh order status.",
    cachedOrderStatus: "Showing the last known order status. Reconnect to refresh.",
    hideReceipt: "Hide receipt",
    viewReceipt: "View receipt",
    printSave: "Print / Save",
    continuePayment: "Continue to payment",
    subtotal: "Subtotal",
    discount: "Discount",
    service: "Service",
    tax: "VAT / Tax",
    cartSummary: "Cart summary",
    item: "item",
    items: "items",
    minuteShort: "min",
    orderType: "Order type",
    payment: "Payment",
    paymentMethod: "Payment method",
    completePayment: "Complete payment",
    paymentPageDescription: "Choose how you paid and submit proof only when the restaurant needs manual review.",
    paymentSafeDescription: "No provider secrets or raw gateway data are shown here.",
    paymentOfflineSubmit: "Connect to the internet before submitting payment. Proof preview stays only in this browser session.",
    paymentSubmitted: "Payment submitted",
    paymentReviewDetails: "Please review payment details.",
    transactionReference: "Transaction reference",
    referenceNumber: "Reference number",
    proofImage: "Proof image",
    proofPreview: "Proof preview",
    proofPreviewAlt: "Selected payment proof preview",
    bakongQrHelp: "Submit to generate a Bakong KHQR code for this order total.",
    bakongScanHelp: "Scan this QR payload with a Bakong-compatible banking app.",
    submitPayment: "Submit payment",
    offlineCached: "You are offline. Showing the last saved menu; prices and availability may have changed.",
    offlineMissing: "You are offline and this menu has not been saved on this device yet.",
    offlineRefresh: "You are offline. Connect to the internet to refresh the menu and submit orders.",
    offlineSubmit: "Connect to the internet before submitting your order.",
    offlineTitle: "You are offline",
    popularNow: "Popular right now",
    products: "Products",
    quantity: "Quantity",
    remove: "Remove",
    required: "Required",
    reviewCart: "Please review your cart.",
    reviewCartBeforeCheckout: "Review items and checkout",
    returnToMenu: "Return to menu",
    searchMenu: "Search menu",
    soldOut: "Sold out",
    specialInstructions: "Special instructions",
    specialInstructionsPlaceholder: "Less sugar, no spicy, extra ice...",
    submitOrder: "Submit order",
    submitting: "Submitting...",
    takeaway: "Takeaway",
    total: "Total",
    tryAnotherSearch: "Try another category or search term.",
  },
  km: {
    addToCart: "បន្ថែមទៅកន្ត្រក",
    addedToCart: "បានបន្ថែម",
    cart: "កន្ត្រក",
    cartEmpty: "កន្ត្រកទទេ",
    backToMenu: "ត្រឡប់ទៅម៉ឺនុយ",
    checkout: "ពិនិត្យការបញ្ជាទិញ",
    checkoutDescription: "ពិនិត្យមុខម្ហូប បន្ថែមព័ត៌មានអតិថិជន ហើយដាក់ការកុម្ម៉ង់ទៅហាង។",
    checkoutStepReview: "ពិនិត្យមុខម្ហូប",
    checkoutStepDetails: "បន្ថែមព័ត៌មាន",
    checkoutStepSend: "ផ្ញើការកុម្ម៉ង់",
    chooseProduct: "ជ្រើសរើសម្ហូបដើម្បីចាប់ផ្តើមបញ្ជាទិញ។",
    clearSearch: "សម្អាតការស្វែងរក",
    customerDetails: "ព័ត៌មានអតិថិជន",
    customerDetailsHelp: "ព័ត៌មាននេះជួយឱ្យហាងបញ្ជាក់ និងរៀបចំការកុម្ម៉ង់។",
    customerName: "ឈ្មោះអតិថិជន",
    customerPhone: "លេខទូរស័ព្ទ",
    dineIn: "ញាំនៅហាង",
    each: "ក្នុងមួយមុខ",
    emptyCartMessage: "ត្រឡប់ទៅម៉ឺនុយ ហើយជ្រើសរើសម្ហូប។",
    featured: "ណែនាំ",
    free: "ឥតគិតថ្លៃ",
    freshMenu: "ម៉ឺនុយថ្មីៗ រួចរាល់សម្រាប់បញ្ជាទិញ។",
    isRequired: "ត្រូវតែជ្រើសរើស",
    itemTypes: "ប្រភេទមុខទំនិញ",
    loadingMenu: "កំពុងផ្ទុកម៉ឺនុយ...",
    mainBranch: "សាខាគោល",
    menu: "ម៉ឺនុយ",
    noDescription: "មិនមានការពិពណ៌នា",
    noImage: "មិនមានរូបភាព",
    noProductsFound: "រកមិនឃើញមុខម្ហូប",
    optional: "មិនចាំបាច់",
    optionRequiredHelp: "ចាំបាច់សម្រាប់មុខម្ហូបនេះ",
    optionOptionalHelp: "ជម្រើសបន្ថែម",
    orderNote: "កំណត់ចំណាំការបញ្ជាទិញ",
    orderSubmitted: "បានដាក់ការបញ្ជាទិញ",
    orderReceivedDescription: "ការកុម្ម៉ង់របស់អ្នកបានផ្ញើទៅភោជនីយដ្ឋាន។ ផ្ទះបាយនឹងចាប់ផ្តើមរៀបចំ។",
    orderNextStep: "រក្សាទំព័រនេះបើក ដើម្បីតាមដានស្ថានភាពការកុម្ម៉ង់ និងការទូទាត់។",
    orderStatusTimeline: "លំដាប់ស្ថានភាពការកុម្ម៉ង់",
    reconnectOrderStatus: "សូមភ្ជាប់អ៊ីនធឺណិតឡើងវិញ ដើម្បីធ្វើបច្ចុប្បន្នភាពស្ថានភាព។",
    cachedOrderStatus: "កំពុងបង្ហាញស្ថានភាពដែលបានរក្សាទុកចុងក្រោយ។ សូមភ្ជាប់ឡើងវិញដើម្បីផ្ទុកថ្មី។",
    hideReceipt: "លាក់បង្កាន់ដៃ",
    viewReceipt: "មើលបង្កាន់ដៃ",
    printSave: "បោះពុម្ព / រក្សាទុក",
    continuePayment: "បន្តទៅការទូទាត់",
    subtotal: "តម្លៃមុខម្ហូប",
    discount: "បញ្ចុះតម្លៃ",
    service: "ថ្លៃសេវា",
    tax: "អាករ",
    cartSummary: "សង្ខេបកន្ត្រក",
    item: "មុខ",
    items: "មុខ",
    minuteShort: "នាទី",
    orderType: "ប្រភេទការបញ្ជាទិញ",
    payment: "ការទូទាត់",
    paymentMethod: "វិធីទូទាត់",
    completePayment: "បញ្ចប់ការទូទាត់",
    paymentPageDescription: "ជ្រើសរើសវិធីដែលអ្នកបានទូទាត់ ហើយបង្ហោះភស្តុតាងតែពេលហាងត្រូវការពិនិត្យ។",
    paymentSafeDescription: "ទំព័រនេះមិនបង្ហាញលេខសម្ងាត់ provider ឬទិន្នន័យ gateway ដើមទេ។",
    paymentOfflineSubmit: "សូមភ្ជាប់អ៊ីនធឺណិត មុនពេលដាក់ការទូទាត់។ រូបភាពភស្តុតាងបង្ហាញតែនៅក្នុង session browser នេះប៉ុណ្ណោះ។",
    paymentSubmitted: "បានដាក់ការទូទាត់",
    paymentReviewDetails: "សូមពិនិត្យព័ត៌មានការទូទាត់។",
    transactionReference: "លេខយោងប្រតិបត្តិការ",
    referenceNumber: "លេខយោង",
    proofImage: "រូបភាពភស្តុតាង",
    proofPreview: "មើលភស្តុតាង",
    proofPreviewAlt: "មើលរូបភាពភស្តុតាងដែលបានជ្រើស",
    bakongQrHelp: "ដាក់ស្នើដើម្បីបង្កើត Bakong KHQR សម្រាប់ចំនួនទឹកប្រាក់នេះ។",
    bakongScanHelp: "ស្កេន QR នេះជាមួយកម្មវិធីធនាគារដែលគាំទ្រ Bakong។",
    submitPayment: "ដាក់ការទូទាត់",
    offlineCached: "អ្នកកំពុងគ្មានអ៊ីនធឺណិត។ កំពុងបង្ហាញម៉ឺនុយដែលបានរក្សាទុកចុងក្រោយ តម្លៃ និងភាពអាចរកបានអាចផ្លាស់ប្តូរ។",
    offlineMissing: "អ្នកកំពុងគ្មានអ៊ីនធឺណិត ហើយម៉ឺនុយនេះមិនទាន់បានរក្សាទុកលើឧបករណ៍នេះទេ។",
    offlineRefresh: "អ្នកកំពុងគ្មានអ៊ីនធឺណិត។ ភ្ជាប់អ៊ីនធឺណិតដើម្បីធ្វើបច្ចុប្បន្នភាពម៉ឺនុយ និងដាក់ការបញ្ជាទិញ។",
    offlineSubmit: "សូមភ្ជាប់អ៊ីនធឺណិត មុនពេលដាក់ការបញ្ជាទិញ។",
    offlineTitle: "អ្នកកំពុងគ្មានអ៊ីនធឺណិត",
    popularNow: "ពេញនិយមឥឡូវនេះ",
    products: "មុខម្ហូប",
    quantity: "ចំនួន",
    remove: "លុបចេញ",
    required: "ចាំបាច់",
    reviewCart: "សូមពិនិត្យកន្ត្រករបស់អ្នក។",
    reviewCartBeforeCheckout: "ពិនិត្យមុខម្ហូប និងបញ្ជាទិញ",
    returnToMenu: "ត្រឡប់ទៅម៉ឺនុយ",
    searchMenu: "ស្វែងរកម៉ឺនុយ",
    soldOut: "អស់ពីស្តុក",
    specialInstructions: "សំណូមពរពិសេស",
    specialInstructionsPlaceholder: "ស្ករតិច មិនហឹរ បន្ថែមទឹកកក...",
    submitOrder: "ដាក់ការបញ្ជាទិញ",
    submitting: "កំពុងដាក់...",
    takeaway: "ខ្ចប់យកទៅ",
    total: "សរុប",
    tryAnotherSearch: "សូមសាកល្បងប្រភេទផ្សេង ឬពាក្យស្វែងរកផ្សេង។",
  },
};

export function normalizeLocale(locale) {
  return supportedLocales.some((item) => item.code === locale) ? locale : "en";
}

export function getPreferredLocale() {
  return normalizeLocale(localStorage.getItem(localeKey) || navigator.language?.slice(0, 2));
}

export function setPreferredLocale(locale) {
  const normalized = normalizeLocale(locale);
  localStorage.setItem(localeKey, normalized);

  return normalized;
}

export function t(locale, key) {
  const normalized = normalizeLocale(locale);

  return dictionary[normalized]?.[key] || dictionary.en[key] || key;
}
